import turtle 
def drawSquare(num):
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.left(30)
    
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.left(30)
    
    turtle.forward(250)
    turtle.left(90)
    turtle.forward(250)
    turtle.left(90)
    turtle.forward(250)
    turtle.left(90)
    turtle.forward(250)
    turtle.left(90)
    turtle.left(30)
    
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.left(30)

    
thenumber = turtle.numinput('','Enter square side size:')
turtle.hideturtle()
thenumber = int(thenumber)
drawSquare(thenumber)